### ISSUE TITLE
Example code does not run

### ISSUE THREAD

**Issue by AndrewDDavis** [lukassnoek/skbold#4]
I like the look of your package -- I was just trying to run the example code. Using the current master, when I run:

    from skbold.feature_extraction import RoiIndexer

 I get:

    ImportError: cannot import name 'RoiIndexer' from 'skbold.feature_extraction'

**Comment by lukassnoek** [comment]
Hi Andrew, I haven't worked on/used this package for years, so I'd advise you to use the Nilearn package instead, which offers most of the functionality from skbold!

**Comment by AndrewDDavis** [comment]
Fair enough, thanks for the tip, Lukas
